[package]
name = "sgf"
description = "SGF parser"
version = "0.1.0"
authors = ["Yuji Ichikawa <ichikawa.yuji@gmail.com>"]
keywords = ["sgf", "parser"]
repository = "https://github.com/y-ich/rust-sgf"
license = "MIT"

[dependencies]
regex = "0.1.47"
